#!/bin/bash
I1=iem1
I2=iem2
d1=domain1
d2=domain2
firewall-cmd --permanent --add-port={8080,443,25,80,143,2525,10000,110,3306}/tcp
firewall-cmd --permanent --add-service={http,https,mysql,smtp,imap,pop3}
firewall-cmd --reload
yum install httpd mariadb mariadb-server sendmail sendmail-cf dovecot php php-* --skip-broken -y
yum install epel-release.noarch -y
yum repolist
yum install php-imap -y
yum remove epel-release -y
systemctl enable httpd mariadb sendmail dovecot
systemctl restart httpd mariadb sendmail dovecot
service postfix stop
systemctl disable postfix
yum remove postfix -y
yum groupinstall base -y

#Configuring Sendmail
#Adding users
for i in {abuse,admin,bounce,fbl,info,noreply,postmaster,support};
do
useradd $i.$d1;
passwd $i.$d1;
mkdir -p /home/$i.$d1/mail/.imap/INBOX  &&  chown -R $i.$d1:$i.$d1 /home/$i.$d1/mail ;
chmod -R 700  /home/$i.$d1/mail ;
echo $i@$d1 $i.$d1 >> /etc/mail/virtusertable
echo $i@$d2 $i.$d2 >> /etc/mail/virtusertable
useradd $i.$d2;
passwd $i.$d2;
mkdir -p /home/$i.$d2/mail/.imap/INBOX  &&  chown -R $i.$d2:$i.$d2 /home/$i.$d2/mail ;
chmod -R 700  /home/$i.$d2/mail ;
echo $i.$d1 $i@$d1 >> /etc/mail/genericstable
echo $i.$d2 $i@$d2 >> /etc/mail/genericstable
#adding $HOSTNAME > /etc/mail/local-host-names
echo $d1 > /etc/mail/local-host-names
echo $d2 >> /etc/mail/local-host-names
#adding $HOSTNAME > /etc/mail/sendmail.gdf
echo $d1 > /etc/mail/sendmail.gdf
echo $d2 >> /etc/mail/sendmail.gdf
done
#config of sendmail.mc
echo "FEATURE(masquerade_envelope)" >> /etc/mail/sendmail.mc
echo "FEATURE(genericstable, \`hash -o /etc/mail/genericstable')" >> /etc/mail/sendmail.mc
echo "FEATURE(masquerade_envelope)" >> /etc/mail/sendmail.mc
echo "add dnl # in line no. 119"
cd /etc/mail
make ; make all
m4 /etc/mail/sendmail.mc /etc/mail/sendmail.cf
service sendmail restart ; service dovecot restart
#IEM Configuration
egrep --color 'upload_max_filesize|max_execution_time|memory_limit|post_max_size' /etc/php.ini
sed -i 's/max_execution_time = 30/max_execution_time = 300/g' /etc/php.ini
sed -i 's/memory_limit = 128/memory_limit = 512/g' /etc/php.ini
sed -i 's/post_max_size = 8/post_max_size = 80/g' /etc/php.ini
sed -i 's/upload_max_filesize = 2/upload_max_filesize = 50/g' /etc/php.ini
service httpd restart
unzip /opt/License_iem_fbl_import_spam_emailmarketer.zip
mv /opt/License_iem_fbl_import_spam_emailmarketer /var/www/html/$I1
chmod -R 777 /var/www/html
chmod -R 777 /var/www/html/*
chmod -R 777 /var/www/html/$I1
chmod -R 777 /var/www/html/$I1/*
unzip /opt/License_iem_fbl_import_spam_emailmarketer.zip
mv /opt/License_iem_fbl_import_spam_emailmarketer /var/www/html/$I2
chmod -R 777 /var/www/html
chmod -R 777 /var/www/html/*
chmod -R 777 /var/www/html/$I2
chmod -R 777 /var/www/html/$I2/*
service httpd restart
#PMTA installation
cd /
tar xzvf /opt/pmta4.tar.gz
rpm -ivh /pmta4/40.rpm
cp -rvf /pmta4/pmtal64f_87048943/etc/pmta/license /etc/pmta/license
systemctl start pmta
systemctl enable pmta
echo "add a pmta key in /etc/pmta/domainname1.key"
echo "add a pmta key in /etc/pmta/domainname2.key"
#PMTA script
#!/bin/bash
# Multi Domain Configuration.
if [ -f newpmta ]
then
 rm -v newpmta
 echo "file newpmta is deleted successfully, you can go ahead"
else
echo "newpmta does not exist, now you can proceed"
fi
clear
echo -e "\t\t\tpls enter hostname: \c"
read hostname
echo -e "\t\t\tpls enter default virtual mta for whole server: \c"
read foralldvmta
echo -e "smtp-listener `ifconfig | sed -n '1,3p' | grep "inet addr" | awk '{print $2}' | cut -d\: -f2`:2525
dont-seek true
http-access 0/0  monitor
http-mgmt-port 1011
host-name $hostname
total-max-smtp-in 1000
total-max-smtp-out 3000
#domain-key dkim,*,/etc/pmta/dkim.key

log-file /var/log/pmta/log            # logrotate is used for rotation

<acct-file /var/log/pmta/acct.csv>
        max-size 50M
</acct-file>

# transient errors (soft bounces)
<acct-file /var/log/pmta/diag.csv>
 delete-after 600d
 records t
</acct-file>

spool /var/spool/pmta
#spool-max-recipients 10000000

<source 127.0.0.1>
 smtp-service yes                # allow SMTP service
 always-allow-relaying yes   # allow feeding from 127.0.0.1
 process-x-virtual-mta yes   # allow selection of a virtual MTA
 remove-received-headers true
 add-received-header false
 hide-message-source true
 default-virtual-mta $foralldvmta
</source>

<source 0/0>
allow-unencrypted-plain-auth yes
process-x-virtual-mta yes   # allow selection of a virtual MTA
max-message-size 0              # 0 implies no cap, in bytes
smtp-service yes                # allow SMTP service
log-commands no
log-connections yes
add-message-id-header yes
add-received-header yes
accept-invalid-recipients no
#verp-default  yes
default-virtual-mta $foralldvmta
#pattern-list myList
</source>" >> newpmta

pmtapool(){
echo -e "\t\t\tpls enter domain name: \c"
read domain
echo -e "\t\t\tpls enter default virtual mta: \c"
read dvmta
echo -e "\t\t\tpls enter appip: \c"
read appip
echo -e "\t\t\tpls enter source name: \c"
read smtpsource
echo -e "\t\t\tpls enter smtp password: \c"
read smtppass
echo -e "enter three octat of ip(prefix): \c"
read ip
echo -e "enter fourth octat of ip(start ip range from): \c"
read ipstart
echo -en "enter fourth octat of ip(end ip range to):"
read ipend
echo -e "enter content of file ap and press ctl+d to save file"
cat > ap

echo -e "############################################## ($domain) ###################################################

postmaster postmaster@$domain
domain-key dkim,$domain,/etc/pmta/`echo $domain | cut -d\. -f1`.key

<smtp-user `echo $domain | cut -d\. -f1`>
        password "$smtppass"
source {$smtpsource}
</smtp-user>

<domain $domain>
   route [$appip]:25
</domain>

<source {$smtpsource}>
always-allow-relaying yes # allow feeding for defined users
process-x-virtual-mta yes # allow selection of a VirtualMTA
max-message-size 0 #implies no cap, in bytes
smtp-service yes # allow SMTP service
require-auth true
add-message-id-header yes
accept-invalid-recipients no
add-message-id-header yes
verp-default  yes
default-virtual-mta $dvmta
#pattern-list blocking-errors
</source>" >> newpmta

echo -e "1 -> To create simple PMTA Pool (virtual-mta)\n2 -> To create auto-cold PMTA Pool Format (auto-cold-virtual-mta)\nPlease enter 1 OR 2: \c" poolf
read poolf
            case $poolf in
            1)
for i in $(seq $ipstart $ipend)
do
            for n in $(cat ap)
            do
            sed -i 1d ap
            echo -e "\n<virtual-mta vmta-$i>
            smtp-source-host  $ip.$i  $n.$domain
</virtual-mta>"
            break
            done
done >> newpmta;;
        2)
for i in $(seq $ipstart $ipend)
do
            for n in $(cat ap)
            do
            sed -i 1d ap
            echo -e "\n<virtual-mta vmta-$i>
                  auto-cold-virtual-mta  $ip.$i  $n.$domain
<domain *>
                  max-cold-virtual-mta-msg 8000/day
</domain>
</virtual-mta>"
            break
            done
done >> newpmta;;
        *) echo -e "Invalid Input";;
esac


echo -e "\n<virtual-mta-pool $dvmta>" >> newpmta
for i in $( seq $ipstart $ipend)
do
echo "virtual-mta  vmta-$i"
done >> newpmta
echo -e "</virtual-mta-pool>\n" >> newpmta
}
clear
echo -e "\t\t\tEnter number to configure pmta for how many domain: \c"
read no
for i in `seq 1 $no`
do
pmtapool
done

echo -e "#################################################### DOMAIN ########################################################

domain-macro hotmail hotmail.com, hotmail.fr, live.com, hotmail.co.uk, hotmail.it, windowslive.com, live.fr, hotmail.de, hotmail.es, live.co.uk, live.it, hotmail.co.jp, live.com.mx, live.nl, live.de, live.cn, live.ru, live.ca, live.com.ar, hotmail.co.th, live.com.au, live.jp, live.se, live.cl, live.com.pt, live.be, live.dk, hotmail.com.tr, livemail.tw, live.no, hotmail.se, hotmail.com.tw, live.co.kr, hotmail.co.nz, live.at, live.in, hotmail.gr, hotmail.be,live.hk, live.ie, msn.cn, hotmail.co.kr, hotmail.no, hotmail.ch, live.co.za, hotmail.com.hk, live.com.my, live.com.sg, hotmail.fi, hotmail.my, hotmail.co.id, hotmail.sg, hotmail.com.au, hotmail.co.za, hotmail.dk, hotmail.rs, live.com.ph, hotmail.ph, hotmail.com.vn, hotmail.cz, w.cn, msn.com

domain-macro yahoo yahoo.com, ymail.com, rocketmail.com, yahoo.co.uk, yahoo.fr, yahoo.com.br, yahoo.co.in, yahoo.ca, yahoo.com.ar, yahoo.com.cn, yahoo.com.mx, yahoo.co.kr, yahoo.co.nz, yahoo.com.hk, yahoo.com.sg, yahoo.es, yahoo.gr, yahoo.de, yahoo.com.ph, yahoo.com.tw, yahoo.ie, yahoo.it, yahoo.se, yahoo.com.au, yahoo.co.id

domain-macro aol aol.com,aim.com,wmconnect.com,aol.com.au,aol.com.mx,aol.com.ar,compuserve.com,aim.com,cs.com,aol.fr, aol.de, aol.in, aol.nl, aol.co.uk, aol.pl, aol.jp, aol.es, aol.it, jp.aol.com

domain-macro gmail gmail.com, googlemail.com

domain-macro ru rambler.ru, yandex.ru, mail.ru, ngs.ru, ya.ru, bk.ru, list.ru, volgafin.ru, inbox.ru

domain-macro orange wanadoo.fr, orange.fr, alerteorange.fr, ville-orange.fr, insolite.net, declictheatre.net, sarlequinoxe.fr, jprfinances.fr, sandra-tentation.com,  cincinnativr.fr,  dreamteamcar.com,  chela.fr,  gert.fr,  soexou.com,  zenith-de-rouen.com, simp.fr,  apasdegeant.fr,  alc57.fr,  carredartnegoce.com, tlm18.com,  oorange.fr, eoleduvigneau.fr, print-technologies.fr, cardiff-soft.com, faprelec.com, meynadier.fr, agencenewdeco.com,  mecadynamic.com, cardiolescedres.com, tirloy.fr, agence-expert.com,  ingeco.fr, blanchardautomobiles.fr, arcol.fr,  macopat.fr,  arca3.fr,  groupe-ams.com,  boinfo.fr, fountlit.com,  garagedegreve.fr,  l2gauto.com, g-el.fr,  jdh-avocats.com, dearinvestconseil.com, mohican-france.fr,  bfba.fr, sts-ca.fr, lyon-duchere.com, asd57.com, charlottedesign.fr, pave.fr

<domain \$gmail>
 queue-priority 75
</domain>

<domain yahoo.co.in>
 queue-priority 72
</domain>

<domain \$yahoo>
 queue-priority 70
</domain>

<domain \$hotmail>
 queue-priority 65
</domain>

<domain \$ru>
 queue-priority 60
</domain>

<domain libero.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>

<domain tin.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>

<domain alice.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>

<domain inwind.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>

<domain att.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-msg-rate 120/h			#  no more than 100 recipients per email message
</domain>

<domain comcast.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2

    max-msg-rate 2/min			# no more than 1000 emails (recipients) per Day
    max-cold-virtual-mta-msg 1200/d
</domain>


<domain verizon.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-errors-per-connection 10

    max-msg-rate 6/min			# no more than 500 emails (recipients) per hour
    max-rcpt-per-message 2
</domain>

<domain \$ru>
    max-smtp-out 2
    max-msg-per-connection 2
    max-errors-per-connection 10

    max-msg-rate 10/min
    max-rcpt-per-message 2
</domain>

<domain earthlink.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    max-msg-rate 2/min			# no more than 1000 emails (recipients) per Day
    max-cold-virtual-mta-msg 1000/d
</domain>

<domain cablevision.com>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    connect-timeout 300s
    smtp-greeting-timeout 500s
    data-send-timeout 600s
    retry-after 5m  # typical greylisting period
    bounce-after 5d  # default 4d12h


    max-msg-rate 2/min			# maximum 50 recipients at one time
    max-cold-virtual-mta-msg 1000/d
</domain>

<domain optimum.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    connect-timeout 300s
    smtp-greeting-timeout 500s
    data-send-timeout 600s
    retry-after 5m  # typical greylisting period
    bounce-after 5d  # default 4d12h


    max-msg-rate 2/min			# maximum 50 recipients at one time
    max-cold-virtual-mta-msg 1000/d
</domain>


<domain roadrunner.com>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    max-msg-rate 2/min			# max 1,000 recipients per day per IP
    max-cold-virtual-mta-msg 1000/d
</domain>

<domain forum.dk>
  type discard
</domain>

<domain cox.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    max-msg-rate 2/min			# max 1,000 recipients per day per IP
    max-cold-virtual-mta-msg 1000/d
</domain>


<domain cox.com>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    max-msg-rate 2/min			# max 1,000 recipients per day per IP
    max-cold-virtual-mta-msg 1000/d
</domain>

<domain charter.com>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    max-msg-rate 1/min			# maximum 50 recipients / emails per hour
</domain>


<domain charter.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10

    max-msg-rate 1/min			# maximum 50 recipients / emails per hour
</domain>

<domain bellsouth.net>
    max-smtp-out 1
    max-msg-per-connection 1
    max-rcpt-per-message 2
    max-errors-per-connection 10
    retry-after 5m

    max-msg-rate 2/min			# maximum 50 recipients / emails per hour
</domain>

<domain virgilio.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>

<domain yahoo.dk>
    max-smtp-out 32
    max-msg-per-connection 32
    max-rcpt-per-message 32
    max-msg-rate 3840/h
</domain>

<domain fastwebnet.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>


<domain iol.it>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>

<domain in.com>
    max-smtp-out 2
    max-msg-per-connection 10
    max-msg-rate 200/h
</domain>

<domain adelphia.net>
    max-smtp-out 2
    max-msg-rate 200/h
</domain>


<domain mac.com>
    ignore-chunking yes
    max-msg-rate 200/h
</domain>

<domain \$orange>
    max-smtp-out 5
    max-msg-per-connection 5
    max-msg-rate 500/h
</domain>

<domain rediffmail.com>
    max-smtp-out 3
    max-msg-per-connection 10
    max-rcpt-per-message 3
    max-msg-rate 300/h
</domain>

<domain rediff.com>
    max-smtp-out 3
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 300/h
</domain>

<domain optonline.net>
    max-smtp-out 2
    max-msg-per-connection 10
    max-rcpt-per-message 2
    max-msg-rate 200/h
</domain>


<domain \$hotmail>
  max-smtp-out 5
  max-msg-per-connection 10
  max-errors-per-connection 10
  max-msg-rate 500/h
  bounce-upon-no-mx yes  # proper mail domains should have mx
  assume-delivery-upon-data-termination-timeout yes  # avoid duplicate deliveries
  connect-timeout 300s
  smtp-greeting-timeout 500s
  data-send-timeout 600s
  retry-after 60m  # typical greylisting period
  bounce-after 3d  # default 4d12h

  smtp-pattern-list blocking-errors
  backoff-max-msg-rate 50/m  # send only regular tries during backoff (default unlimited)
  backoff-retry-after 1h  # retry at least every 20m (default 1h)
  #backoff-notify   # disable backoff notifications
  backoff-to-normal-after-delivery yes  # revert to normal asap (default no)
  backoff-to-normal-after 1h  # always revert to normal after 1h (default never)

  dk-sign yes
  dkim-sign yes
</domain>

<domain \$yahoo>
  max-msg-per-connection 10 # yahoo policy
  max-smtp-out 15  # default be nice on concurrent connections
  max-errors-per-connection 10  # avoid 'too long without data command' error

  max-msg-rate 2500/h
  bounce-upon-no-mx yes  # proper mail domains should have mx
  assume-delivery-upon-data-termination-timeout yes  # avoid duplicate deliveries
  connect-timeout 120s
  smtp-greeting-timeout 500s
  data-send-timeout 300s
  retry-after 60m  # typical greylisting period
  bounce-after 3d  # default 4d12h

  smtp-pattern-list blocking-errors
  backoff-max-msg-rate 50/m  # send only regular tries during backoff (default unlimited)
  backoff-retry-after 1h  # retry at least every 20m (default 1h)
  #backoff-notify   # disable backoff notifications
  backoff-to-normal-after-delivery yes  # revert to normal asap (default no)
  backoff-to-normal-after 1h  # always revert to normal after 1h (default never)

  dk-sign yes
  dkim-sign yes
</domain>

<domain \$aol>
  max-smtp-out 10  # default be nice on concurrent connections
  max-msg-per-connection 10  # max 500 mails in one session
  max-errors-per-connection 2  # avoid 'too long without data command' error

  max-msg-rate 120/h
  bounce-upon-no-mx yes  # proper mail domains should have mx
  assume-delivery-upon-data-termination-timeout yes  # avoid duplicate deliveries
  connect-timeout 300s
  smtp-greeting-timeout 500s
  data-send-timeout 600s
  retry-after 60m  # typical greylisting period
  bounce-after 3d  # default 4d12h

  smtp-pattern-list blocking-errors
  backoff-max-msg-rate 1/m  # send only regular tries during backoff (default unlimited)
  backoff-retry-after 1h  # retry at least every 20m (default 1h)
  #backoff-notify   # disable backoff notifications
  backoff-to-normal-after-delivery yes  # revert to normal asap (default no)
  backoff-to-normal-after 1h  # always revert to normal after 1h (default never)

  dk-sign yes
  dkim-sign yes
</domain>

<domain \$gmail>
  max-smtp-out 10  # default be nice on concurrent connections
  max-msg-per-connection 10 # max 500 mails in one session
  max-errors-per-connection 3  # avoid 'too long without data command' error

  max-msg-rate 1200/h
  bounce-upon-no-mx yes  # proper mail domains should have mx
  assume-delivery-upon-data-termination-timeout yes  # avoid duplicate deliveries
  smtp-421-means-mx-unavailable no
  connect-timeout 300s
  smtp-greeting-timeout 500s
  data-send-timeout 600s
  retry-after 60m  # typical greylisting period
  bounce-after 3d  # default 4d12h

  smtp-pattern-list blocking-errors
  backoff-max-msg-rate 4/h  # send only regular tries during backoff (default unlimited)
  backoff-retry-after 12h  # retry at least every 20m (default 1h)
  #backoff-notify   # disable backoff notifications
  backoff-to-normal-after-delivery yes  # revert to normal asap (default no)
  backoff-to-normal-after 1h  # always revert to normal after 1h (default never)

  dk-sign yes
  dkim-sign yes
</domain>



<domain *>
  max-smtp-out 10  # default be nice on concurrent connections
  max-msg-per-connection 10  # max 500 mails in one session
  max-errors-per-connection 4  # avoid 'too long without data command' error

  max-msg-rate 7000/h
  bounce-upon-no-mx yes  # proper mail domains should have mx
  assume-delivery-upon-data-termination-timeout yes  # avoid duplicate deliveries
  connect-timeout 120s
  smtp-greeting-timeout 500s
  data-send-timeout 600s
  retry-after 60m  # typical greylisting period

  bounce-after 5d  # default 4d12h
  smtp-pattern-list blocking-errors
  backoff-max-msg-rate 10/m  # send only regular tries during backoff (default unlimited)
  backoff-retry-after 1h  # retry at least every 20m (default 1h)
  #backoff-notify   # disable backoff notifications
  backoff-to-normal-after-delivery yes  # revert to normal asap (default no)
  backoff-to-normal-after 1h  # always revert to normal after 1h (default never)

 dk-sign yes
 dkim-sign yes
</domain>
########################################################################################################################################################################
######################################################################### SMTP-PATTERN LIST ############################################################################
########################################################################################################################################################################
<smtp-pattern-list blocking-errors>
#AOL Errors
reply /blocked.*spamhaus/ mode=backoff ,disable-source-ip,reenable-after=24h
reply /RTR:DU/ mode=backoff ,disable-source-ip,reenable-after=2h
reply /RTR:BL/ mode=backoff ,disable-source-ip,reenable-after=4h
reply /RLY:B2/ mode=backoff ,disable-source-ip,reenable-after=4h
reply /RLY:B3/ mode=backoff ,disable-source-ip,reenable-after=30m
#reply /RLY:BD/ bounce-queue
reply /RLY:NW/ mode=backoff ,disable-source-ip,reenable-after=24h
reply /RLY:SN/ bounce-rcpt
reply /RLY:SN/ bounce-rcpt
reply /DYN:T1/ mode=backoff ,disable-source-ip,reenable-after=2h
reply /DYN:T2/ mode=backoff ,disable-source-ip,reenable-after=2h
reply /CON:B1/ mode=backoff ,disable-source-ip,reenable-after=2h


#Yahoo Errors
#reply /421 .* Please try again later/ mode=backoff
reply /temporarily deferred/ bounce-rcpt
reply /VS3-IP5 Excessive unknown recipients/ mode=backoff
reply /VSS-IP Excessive unknown recipients/ mode=backoff
 # The following 4 Yahoo errors may be very common
   # Using them may result in high use of backoff mode
   #
reply /\[GL01\] Message from/ mode=backoff
reply /\[GL01\] Message from/ mode=backoff
reply /\[TS01\] Messages from/ mode=backoff ,disable-source-ip,reenable-after=4m
reply /\[TS02\] Messages from/ mode=backoff ,disable-source-ip,reenable-after=4h
reply /\[TS03\] All messages from/ mode=backoff
reply /Connections not accepted from IP addresses on Spamhaus/ mode=backoff ,disable-source-ip,reenable-after=10h

#Hotmail Errors
reply /exceeded the rate limit/ mode=backoff
reply /exceeded the connection limit/ mode=backoff
reply /Mail rejected by Windows Live Hotmail for policy reasons/ mode=backoff
reply /mail.live.com\/mail\/troubleshooting.aspx/ mode=backoff

#
#Adelphia Errors
#reply /421 Message Rejected/ mode=backoff
#reply /Client host rejected/ mode=backoff
reply /blocked using UCEProtect/ mode=backoff
#
#Road Runner Errors
reply /Mail Refused/ mode=backoff
reply /421 Exceeded allowable connection time/ mode=backoff
reply /amIBlockedByRR/ mode=backoff
reply /block-lookup/ mode=backoff
reply /Too many concurrent connections from source IP/ mode=backoff

#Custom
reply /listed by bl.spamcop.net Blocked/ mode=backoff ,disable-source-ip,reenable-after=4h
#reply /unusual rate of unsolicited mail/ skip-mx
reply /unusual rate of unsolicited mail originating from/ mode=backoff ,disable-source-ip,reenable-after=4h
</smtp-pattern-list>

<bounce-category-patterns>
    /spam/ spam-related
    /junk mail/ spam-related
    /blacklist/ spam-related
    /blocked/ spam-related
    /\bU\.?C\.?E\.?\b/ spam-related
    /\bAdv(ertisements?)?\b/ spam-related
    /unsolicited/ spam-related
    /\b(open)?RBL\b/ spam-related
    /realtime blackhole/ spam-related
    /http:\/\/basic.wirehub.nl\/blackholes.html/ spam-related
    /\bvirus\b/ virus-related
    /message +content/ content-related
    /content +rejected/ content-related
    /quota/ quota-issues
    /limit exceeded/ quota-issues
    /mailbox +(is +)?full/ quota-issues
    /sender ((verify|verification) failed|could not be verified|address rejected|domain must exist)/ invalid-sender
    /unable to verify sender/ invalid-sender
    /requires valid sender domain/ invalid-sender
    /bad sender's system address/ invalid-sender
    /No MX for envelope sender domain/ invalid-sender
    /^[45]\.4\.4/ routing-errors
    /no mail hosts for domain/ invalid-sender
    /Your domain has no(t)? DNS\/MX entries/ invalid-sender
    /REQUESTED ACTION NOT TAKEN: DNS FAILURE/ invalid-sender
    /Domain of sender address/ invalid-sender
    /return MX does not exist/ invalid-sender
    /Invalid sender domain/ invalid-sender
    /Verification failed/ invalid-sender
    /\bstorage\b/ quota-issues
    /(user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee) (has|has been|is)? *(currently|temporarily +)?(disabled|expired|inactive|not activated)/ inactive-mailbox
    /(conta|usu.rio) inativ(a|o)/ inactive-mailbox
    /Too many (bad|invalid|unknown|illegal|unavailable) (user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee)/ other
    /(No such|bad|invalid|unknown|illegal|unavailable) (local +)?(user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee)/ bad-mailbox
    /(user|mailbox|recipient|rcpt|local part|address|account|mail drop|ad(d?)ressee) +(\S+@\S+ +)?(not (a +)?valid|not known|not here|not found|does not exist|bad|invalid|unknown|illegal|unavailable)/ bad-mailbox
    /\S+@\S+ +(is +)?(not (a +)?valid|not known|not here|not found|does not exist|bad|invalid|unknown|illegal|unavailable)/ bad-mailbox
 /no mailbox here by that name/ bad-mailbox
    /my badrcptto list/ bad-mailbox
    /not our customer/ bad-mailbox
    /no longer (valid|available)/ bad-mailbox
    /Recipient address rejected/ bad-mailbox
    /have a \S+ account/ bad-mailbox
    /\brelay(ing)?/ relaying-issues
    /domain (retired|bad|invalid|unknown|illegal|unavailable)/ bad-domain
    /domain no longer in use/ bad-domain
    /domain (\S+ +)?(is +)?obsolete/ bad-domain
    /denied/ policy-related
    /prohibit/ policy-related
    /refused/ policy-related
    /allowed/ policy-related
    /banned/ policy-related
    /policy/ policy-related
    /suspicious activity/ policy-related
    /bad sequence/ protocol-errors
    /syntax error/ protocol-errors
    /\broute\b/ routing-errors
    /\bunroutable\b/ routing-errors
    /\bunrouteable\b/ routing-errors
    /Invalid 7bit DATA/ content-related
    /^2.\d+.\d+;/ success
    /^[45]\.1\.[1346];/ bad-mailbox
    /^[45]\.1\.2/ bad-domain
    /^[45]\.1\.[78];/ invalid-sender
    /^[45]\.2\.0;/ bad-mailbox
    /^[45]\.2\.1;/ inactive-mailbox
    /^[45]\.2\.2;/ quota-issues
    /^[45]\.3\.3;/ content-related
    /^[45]\.3\.5;/ bad-configuration
    /^[45]\.4\.1;/ no-answer-from-host
    /^[45]\.4\.2;/ bad-connection
    /^[45]\.4\.[36];/ routing-errors
    /^[45]\.4\.7;/ message-expired
    /^[45]\.5\.3;/ policy-related
    /^[45]\.5\.\d+;/ protocol-errors
    /^[45]\.6\.\d+;/ content-related
    /^[45]\.7\.[012];/ policy-related
    /^[45]\.7\.7;/ content-related
    // other    # catch-all
</bounce-category-patterns>" >> newpmta
